name: CI

on:
    push:
        branches:
            - main

jobs:
    react-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies and build React app
              run: |
                  cd D:/Frontend/reactjs/weather-ui
                  npm install
                  npm run build

    node-start:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies and start Node server
              run: |
                  cd D:/Frontend/reactjs/weather-ui  # Thay đổi đường dẫn tới thư mục React app của bạn
                  npm install
                  npm start
